# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:31
from __future__ import unicode_literals

import cardapp.models
import ckeditor.fields
import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationOnCardMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Annotations',
                'verbose_name': 'Annotation',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to=cardapp.models.upload_dest, width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('date_created', models.DateField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateField(auto_now=True, db_index=True)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('background_color', colorful.fields.RGBColorField(default='#ffffff')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to=cardapp.models.upload_dest, width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('date_created', models.DateField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateField(auto_now=True, db_index=True)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardOnCardMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapp.Card')),
                ('cardmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapp.CardMap')),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'verbose_name': 'Card',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to=cardapp.models.upload_dest, width_field='image_width')),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('date_created', models.DateField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateField(auto_now=True, db_index=True)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('url', models.URLField(blank=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cardapp.Tag'),
        ),
        migrations.AddField(
            model_name='cardmap',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardmaps', to='cardapp.Deck'),
        ),
        migrations.AddField(
            model_name='cardmap',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cardapp.Tag'),
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cardapp.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cardapp.Tag'),
        ),
        migrations.AddField(
            model_name='annotationoncardmap',
            name='cardmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapp.CardMap'),
        ),
    ]
